/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//inserte sus comentarios aqui
package prototipop1;

import java.awt.Dimension;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author kievk
 */
public class mdi_Principal extends javax.swing.JFrame {

    private static String c;
    private static String u;
    public static String BD = "jdbc:mysql://localhost/sic";
    public static String Usuario = "root";
    public static String Contraseña = "Polo.2015";

   

    
    public static Connection getConeccion() {
        Connection cn = null;
        try {
            Class.forName(BD);
            cn = DriverManager.getConnection(mdi_Principal.BD, mdi_Principal.Usuario, mdi_Principal.Contraseña);

        } catch (Exception e) {
            System.out.println(String.valueOf(e));
        }
        return cn;

    }

    public mdi_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(mdi_Principal.MAXIMIZED_BOTH);
        this.setTitle("Hotel");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelc = new javax.swing.JLabel();
        boton_press = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MenuInventarios = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuCreditoProv = new javax.swing.JMenuItem();
        jmAdministracion = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        labelc.setText("jLabel1");

        boton_press.setText("nombre_boton");

        lbusu.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Mantenimientos");

        MenuInventarios.setText("Mantenimiento Inventarios");
        MenuInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuInventariosMousePressed(evt);
            }
        });
        MenuInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInventariosActionPerformed(evt);
            }
        });
        fileMenu.add(MenuInventarios);

        jMenuItem7.setText("Mantenimiento Proveedor");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem7MousePressed(evt);
            }
        });
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem7);

        menuBar.add(fileMenu);

        jMenu1.setText("Transacciones");

        jMenuItem16.setText("Compras");
        jMenuItem16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem16MousePressed(evt);
            }
        });
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuCreditoProv.setText("Credito Proveedores");
        jMenuCreditoProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuCreditoProvMousePressed(evt);
            }
        });
        jMenuCreditoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreditoProvActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCreditoProv);

        menuBar.add(jMenu1);

        jmAdministracion.setText("Privacidad");

        jMenuItem18.setText("Mantenimiento Rol");
        jMenuItem18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem18MousePressed(evt);
            }
        });
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jmAdministracion.add(jMenuItem18);

        jMenuItem19.setText("Mantenimento Usuario");
        jMenuItem19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem19MousePressed(evt);
            }
        });
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jmAdministracion.add(jMenuItem19);

        menuBar.add(jmAdministracion);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Exit");
        helpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuMouseClicked(evt);
            }
        });
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuMouseClicked
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_helpMenuMouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {
   
    }
    

    private void jMenuCotEncClientesActionPerformed(java.awt.event.ActionEvent evt) {
     

    }

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {
    
    }

    private void jMenuCotDetClientesActionPerformed(java.awt.event.ActionEvent evt) {
      

        // TODO add your handling code here:
    }

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {
     
    }

    private void jMenuCotEncProveedoresActionPerformed(java.awt.event.ActionEvent evt) {
  

        // TODO add your handling code here:
    }


    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        inf_Transaccion_Compras ventana = new inf_Transaccion_Compras();
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
      
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuCreditoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreditoProvActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCreditoProvActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed

    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem16MousePressed
        // TODO add your handling code here:
        String nombre = jMenuItem16.getText();
        boton_press.setText(nombre);
    }//GEN-LAST:event_jMenuItem16MousePressed

    private void jMenuCreditoProvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreditoProvMousePressed
        // TODO add your handling code here:
        String nombre = jMenuCreditoProv.getText();
        boton_press.setText(nombre);
    }//GEN-LAST:event_jMenuCreditoProvMousePressed

    private void jMenuItem18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem18MousePressed
        // TODO add your handling code here:
        String nombre = jMenuItem18.getText();
        boton_press.setText(nombre);
    }//GEN-LAST:event_jMenuItem18MousePressed

    private void jMenuItem19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem19MousePressed
        // TODO add your handling code here:
        String nombre = jMenuItem19.getText();
        boton_press.setText(nombre);
    }//GEN-LAST:event_jMenuItem19MousePressed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        inf_Mantenimiento_Proveedor ventana1 = new inf_Mantenimiento_Proveedor();
        desktopPane.add(ventana1);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana1.getSize();
        ventana1.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MousePressed
        // TODO add your handling code here:
        String nombre = jMenuItem7.getText();
        boton_press.setText(nombre);
    }//GEN-LAST:event_jMenuItem7MousePressed

    private void MenuInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInventariosActionPerformed

    }//GEN-LAST:event_MenuInventariosActionPerformed

    private void MenuInventariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInventariosMousePressed
        // TODO add your handling code here:
        String nombre = MenuInventarios.getText();
        boton_press.setText(nombre);
    }//GEN-LAST:event_MenuInventariosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdi_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuInventarios;
    private javax.swing.JLabel boton_press;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuCreditoProv;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu jmAdministracion;
    public static javax.swing.JLabel labelc;
    public static javax.swing.JLabel lbusu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
